#include <vector>
#include <list>
#include <map>
#include <set>
#include <deque>
#include <queue>
#include <cstdlib>
#include <cstdio>
#include <stack>
#include <algorithm>
#include <iostream>
#include <string>
#include <memory.h>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <cstdlib>
#include <iterator>
#include <ctime>
#define pb push_back
#define mp make_pair      
using namespace std;
 
typedef long long ll;
typedef long double ld;


class KingdomAndDice {

int dp[50+5][50*50+5];

public:
	double newFairness(vector <int> f, vector <int> s, int X) {
		vector<int> v;
		int n = f.size();
		
		int empty = 0;
		int cur = 0;
		for (int i = 0; i < n; i++){
			if (f[i] == 0)
				empty++;
			for (int j = 0; j < n; j++)
				cur += f[i] > s[j];
		}
		
		for (int j = 0; j < empty; j++)
			v.pb(0);
		sort(f.begin(),f.end());
		sort(s.begin(),s.end());
		for (int i = 0; i < n; i++){
			int cnt = 0;
			for (int j = s[i]+1; j <= X && (i == n-1 || j < s[i+1]) && cnt <= empty; j++)
				if (!binary_search(f.begin(),f.end(),j))
					v.pb(i+1),cnt++,cerr << i+1<< " ";
		}
		cerr<<endl;
		
		
		//cerr << cur <<" "<<empty<<endl;
		
		memset(dp,0,sizeof(dp));
		dp[0][cur] = 1;
		
		for (int i = 0; i < (int)v.size(); i++){
			int add = v[i];
			for (int j = empty-1; j >= 0; j--)
				for (int k = cur; k <= j*n+cur; k++)
					if (dp[j][k]){
					    dp[j+1][k+add] = true, dp[j+1][k] = true;
					}
		}
		
		//for (int i = 0; i <= n*n; i++)
		//	cerr << dp[empty][i] ;
		
		if (n % 2 == 0){
			for (int d = 0; ; d++){
				if (dp[empty][(n*n)/2-d])
					return (((n*n)/2-d))*1.0/(n*n);
				
				if (dp[empty][(n*n)/2+d])
					return (((n*n)/2+d))*1.0/(n*n);
			}
			assert(false);
		}
		for (int d = 0; ; d++){
			if (n*n/2-d > 0 && dp[empty][(n*n)/2-d])
				return (((n*n)/2-d))*1.0/(n*n);
			if (dp[empty][(n*n)/2+d-1])
				return (((n*n)/2+d-1))*1.0/(n*n);
		}
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, vector <int> p1, int p2, bool hasAnswer, double p3) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}" << "," << p2;
	cout << "]" << endl;
	KingdomAndDice *obj;
	double answer;
	obj = new KingdomAndDice();
	clock_t startTime = clock();
	answer = obj->newFairness(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p3 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == answer && fabs(p3 - answer) <= 1e-9 * max(1.0, fabs(p3));
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <int> p0;
	vector <int> p1;
	int p2;
	double p3;
	
	{
	// ----- test 0 -----
	int t0[] = {0,2,7,0};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {6,3,8,10};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 12;
	p3 = 0.4375;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	int t0[] = {0,2,7,0};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {6,3,8,10};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 10;
	p3 = 0.375;
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	int t0[] = {0,0};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {5,8};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 47;
	p3 = 0.5;
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	int t0[] = {19,50,4};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {26,100,37};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 1000;
	p3 = 0.2222222222222222;
	all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	int t0[] = {6371,0,6256,1852,0,0,6317,3004,5218,9012};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {1557,6318,1560,4519,2012,6316,6315,1559,8215,1561};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 10000;
	p3 = 0.49;
	all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING


//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
