#include <vector>
#include <list>
#include <map>
#include <set>
#include <deque>
#include <queue>
#include <cstdlib>
#include <cstdio>
#include <stack>
#include <algorithm>
#include <iostream>
#include <string>
#include <cstring>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <iterator>
#include <functional>
#include <bitset>
#include <ctime>
#define pb push_back
#define mp make_pair      
using namespace std;
 
typedef long long ll;
typedef long double ld;


class PenguinSledding {



public:
    ll countDesigns(int n, vector <int> a, vector <int> b) {
        int m = a.size();
        ll ans = 0;
        vector<int> deg(n,0);
        for (int i = 0; i < m; i++)
        	deg[a[i]-1]++, deg[b[i]-1]++;
        for (int i = 0; i < n; i++){
        	ans += (1LL<<deg[i]);
        }
        vector<vector<int> > g(n,vector<int>(n,0));
        for (int i = 0; i < m; i++)
        	g[a[i]-1][b[i]-1] = g[b[i]-1][a[i]-1] = 1;
        	
        for (int i = 0; i < n; i++)
        	for (int j = i+1; j < n; j++)
        		for (int k = j+1; k < n; k++)
        			if (g[i][j] && g[j][k] && g[k][i])
        				ans++;
        return ans - m - n + 1;
    }
};







// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, vector <int> p1, vector <int> p2, bool hasAnswer, ll p3) {
	cout << "Test " << testNum << ": [" << p0 << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p2.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p2[i];
	}
	cout << "}";
	cout << "]" << endl;
	PenguinSledding *obj;
	ll answer;
	obj = new PenguinSledding();
	clock_t startTime = clock();
	answer = obj->countDesigns(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p3 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p3;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	int p0;
	vector <int> p1;
	vector <int> p2;
	ll p3;
	
	{
	// ----- test 0 -----
	p0 = 2;
	int t1[] = {1};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {2};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 2ll;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	p0 = 4;
	int t1[] = {1,2,3};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {2,3,4};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 6ll;
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	p0 = 6;
	int t1[] = {1,3,6};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {2,4,4};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 5ll;
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	p0 = 50;
	int t1[] = {40,40,40,40,40,40,40,40,40,40,40,40,50,40,40,40,23,4,24,40,22,40,8,40,40,40,34,21,40,40,38,40,40,40,40,40,28,40,40,40,40,46,13,40,40,40,47,40,40};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {45,42,20,48,12,32,25,10,26,39,16,2,19,43,37,17,19,19,19,18,19,27,19,29,11,36,19,19,1,41,19,35,14,33,49,3,19,7,5,19,31,19,19,6,9,15,19,44,30};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 68719493118ll;
	all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	p0 = 36;
	int t1[] = {13,24,24,20,31,16,10,36,34,32,28,5,20,29,23,2,14,4,9,5,19,21,8,1,26,27,25,15,22,30,30,6,11,7,2,35,13,29,4,12,33,18,13,14,17,35,3};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {10,15,27,1,29,11,5,18,33,1,9,2,31,6,19,10,33,18,6,27,3,22,4,12,31,30,34,16,7,24,3,28,15,21,22,8,26,20,14,32,25,17,35,8,36,26,23};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 162ll;
	all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
